CREATE DATABASE IF NOT EXISTS markovic;

USE markovic;

CREATE TABLE IF NOT EXISTS corpora (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  datum TEXT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8;

